# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPetstore():
    def setup_method(self, method):
        self.driver = webdriver.Chrome('E:/Users/Léo/PycharmProjects/fts132_inicial/drivers/chrome/103/chromedriver.exe')
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_petstore(self):
        self.driver.get("https://petstore.swagger.io/")
        self.driver.set_window_size(1565, 847)
        self.driver.find_element(By.CSS_SELECTOR, ".download-url-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".topbar-wrapper").click()
        self.driver.find_element(By.CSS_SELECTOR, ".download-url-input").send_keys("petstore")
        self.driver.find_element(By.CSS_SELECTOR, ".download-url-input").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".title").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".title").click()
        self.driver.find_element(By.CSS_SELECTOR, ".title").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".title").text == "Failed to load API definition."
        assert self.driver.find_element(By.CSS_SELECTOR, ".title").text == "Failed to load API definition."
